spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  default-produces-media-type: application/json
